[package]
name = "linuxcnc-hal"
version = "0.1.0"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"
keywords = [ "cnc", "linuxcnc" ]
categories = [ "api-bindings" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.linuxcnc-hal-sys]
path = "../linuxcnc-hal-sys"
