version: 2
jobs:
  build:
    resource_class: large
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - restore_cache:
          key:
            v2-linuxcnc-hal-rs-{{ .Environment.RUST_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{
            checksum "linuxcnc-hal-sys/Cargo.toml" }}-{{ checksum "linuxcnc-hal/Cargo.toml" }}
      - run:
          sudo apt update -qq && sudo apt install -qq --no-install-suggests python3-pip libclang-dev
          llvm-dev libclang-dev clang
      - run: pip3 install linkchecker

      # Set up LinuxCNC with some hacks
      - run: |
          LINUXCNC_HASH="37cc349c29"

          git clone https://github.com/LinuxCNC/linuxcnc.git linuxcnc
          cd linuxcnc
          git checkout "${LINUXCNC_HASH}"
      - run: cp ".circleci/liblinuxcnchal.so.0-${LINUXCNC_HASH}" ./linuxcnc/lib/liblinuxcnchal.so.0
      - run: ln -s realpath(./linuxcnc/lib/liblinuxcnchal.so.0) realpath(./linuxcnc/lib/liblinuxcnchal.so)

      - run: rustup component add rustfmt
      - run: rustup toolchain add nightly
      - run: rustup default ${RUST_VERSION:-stable}
      - run: LINUXCNC_SRC=$(realpath ./linuxcnc) ./build.sh
      - save_cache:
          key:
            v2-linuxcnc-hal-rs-{{ .Environment.RUST_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{
            checksum "linuxcnc-hal-sys/Cargo.toml" }}-{{ checksum "linuxcnc-hal/Cargo.toml" }}
          paths:
            - ./target
            - /home/circleci/.cargo/registry

build_jobs: &build_jobs
  jobs:
    - build

workflows:
  version: 2
  build_all:
    <<: *build_jobs

  # # Build every day
  # nightly:
  #   <<: *build_jobs
  #   triggers:
  #     - schedule:
  #         cron: '0 0 * * *'
  #         filters:
  #           branches:
  #             only:
  #               - master
