version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.40.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: v1-linuxcnc-hal-rs-{{ .Environment.RUST_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "linuxcnc-hal-sys/Cargo.toml" }}-{{ checksum "linuxcnc-hal/Cargo.toml" }}
      - run: sudo apt install -qq python-pip
      - run: sudo pip install linkchecker
      - run: rustup default ${RUST_VERSION:-stable}
      - run: rustup component add rustfmt
      - run: ./setup.sh
      - run: ./build.sh
      - save_cache:
          key: v1-linuxcnc-hal-rs-{{ .Environment.RUST_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "linuxcnc-hal-sys/Cargo.toml" }}-{{ checksum "linuxcnc-hal/Cargo.toml" }}
          paths:
            - ./target
            - /home/ubuntu/.cargo

build_jobs: &build_jobs
  jobs:
    - build

workflows:
  version: 2
  build_all:
    <<: *build_jobs

  # Build every day
  nightly:
    <<: *build_jobs
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
