version: 2
jobs:
  build:
    resource_class: large
    docker:
      - image: cimg/rust:1.65.0
    environment:
      - LINUXCNC_SRC: ./linuxcnc
    steps:
      - checkout
      - restore_cache:
          key:
            v1-linuxcnc-hal-rs-{{ .Environment.RUST_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{
            checksum "linuxcnc-hal-sys/Cargo.toml" }}-{{ checksum "linuxcnc-hal/Cargo.toml" }}
      - run:
          sudo apt update -qq && sudo apt install -qq --no-install-suggests python3-pip libclang-dev
          llvm-dev libclang-dev clang
      - run: pip3 install linkchecker
      - run: git clone https://github.com/LinuxCNC/linuxcnc.git linuxcnc
      - run: rustup component add rustfmt
      - run: rustup toolchain add nightly
      - run: rustup default ${RUST_VERSION:-stable}
      - run: ./build.sh
      - save_cache:
          key:
            v1-linuxcnc-hal-rs-{{ .Environment.RUST_VERSION }}-{{ .Environment.CIRCLE_JOB }}-{{
            checksum "linuxcnc-hal-sys/Cargo.toml" }}-{{ checksum "linuxcnc-hal/Cargo.toml" }}
          paths:
            - ./target
            - /home/ubuntu/.cargo

build_jobs: &build_jobs
  jobs:
    - build

workflows:
  version: 2
  build_all:
    <<: *build_jobs

  # # Build every day
  # nightly:
  #   <<: *build_jobs
  #   triggers:
  #     - schedule:
  #         cron: '0 0 * * *'
  #         filters:
  #           branches:
  #             only:
  #               - master
